name: Haven-OG
author: NotAlexNoyle
description: WorldGuard haven regions for hostile mob entry and targeting control.
website: https://github.com/true-og/Haven-OG/
version: '${version}'
api-version: '${apiVersion}'
main: net.trueog.havenog.HavenOG
depend:
  - WorldGuard
